### ISSUE TITLE
'$' at the end of every line 

### ISSUE THREAD

**Issue by snkshukla** [thaerkh/vim-indentguides#1]
It is looking weird, is there any way to put them off, is that a feature?
![screen shot](https://user-images.githubusercontent.com/16763730/27119195-810926a0-50fc-11e7-8a48-7767242d1185.png)

**Comment by thaerkh** [comment]
Hi @snkshukla,

This is due to the default `listchars` value in Vim - you can override it by adding `set listchars=""` to your vimrc.

Cheers,
Thaer

**Comment by Adityashaw** [comment]
> Hi @snkshukla,
> 
> This is due to the default `listchars` value in Vim - you can override it by adding `set listchars=""` to your vimrc.
> 
> Cheers,
> Thaer

@thaerkh Sir, I tried adding the above line but it then makes the plug-in work in some uncertain way. Please help.

1. Contents of .vimrc

```

" Vim's auto indentation feature does not work properly with text copied from outisde of Vim. Press the <F2> key to toggle paste mode on/off.
nnoremap <F2> :set invpaste paste?<CR>
imap <F2> <C-O>:set invpaste paste?<CR>
set pastetoggle=<F2>

" Set line  numbers
set number

" Make tab to look like 4 spaces
set tabstop=4
set shiftwidth=4
set softtabstop=4

" Highlight matching search patterns
set hlsearch
" Enable incremental search
set incsearch
" Include matching uppercase words with lowercase search term
set ignorecase
" Include only uppercase words with uppercase search term
set smartcase

" To remove $ at end of lines due to indentation plug-in
set listchars=""

" Call the .vimrc.plug file
if filereadable(expand("~/.vimrc.plug"))
	source ~/.vimrc.plug
endif
```
2. Contents of .vimrc.plug

```
call plug#begin('~/.vim/plugged')

"Fugitive Vim Github Wrapper
"Plug 'tpope/vim-fugitive'

"Asynchronous Lint Engine
Plug 'w0rp/ale'

" Display Indent Levels Visually
"Plug 'nathanaelkane/vim-indent-guides'
"let g:indent_guides_enable_on_vim_startup = 1
"let g:indent_guides_guide_size = 1
Plug 'thaerkh/vim-indentguides'

call plug#end()
```
![Screenshot from 2019-05-28 01-36-59](https://user-images.githubusercontent.com/10658508/58437795-3bc4cf80-80e9-11e9-96df-933b6639b35b.png)

**Comment by edyatl** [comment]
You can unset list mode by statement below in your .vimrc 
let g:indentguides_toggleListMode = 0
