### ISSUE TITLE
indent chars

### ISSUE THREAD

**Issue by pKm49** [thaerkh/vim-indentguides#2]
I would like to know how to change the indent characters. I want to use other symbols instead of | and $.

**Comment by thaerkh** [comment]
Hi @pKm49 ,

That's a reasonable request. I've submitted a commit that to allows one to customise space and tab characters.
Change the following in your vimrc to suit your preferences:
```
let g:indentguides_spacechar = '┆'
let g:indentguides_tabchar = '|'
 ```
