### ISSUE TITLE
Turning the guide display off does not return conceallevel=0

### ISSUE THREAD

**Issue by EdmundsEcho** [thaerkh/vim-indentguides#3]
When I invoke `:IndentGuidesToggle` to hide the guides, the double quotes remain hidden (hiding the quotes is a separate issue).  
I expect the command to reset the the `conceallevel=0` to show the hidden double quotes
Instead, I have to manually set the `conceallevel=0`

**Comment by thaerkh** [comment]
Hi Edmunds,

When toggling the plugin off, it resets local conceallevel to the global value set by the user, and I suspect yours is not 0. For instance, my default Vim behaviour for Latex filetypes has conceallevel set to 2, and if I toggle indents off (using the mentioned command) it resets to my global value that happens to be 0.

Cheers,
Thaer
