### ISSUE TITLE
existing listchars is changed, list mode always activated

### ISSUE THREAD

**Issue by Claudius42** [thaerkh/vim-indentguides#4]
It's a great plugin but I faced two issues:
1) list mode is always activated and
2) g:listchars got always changed even though 'tab:' and 'trail:' was already set within my vimrc
I slightly adapted the plugin to solve both issues. If I shall/can contribute my changes via github please let me know how to do so.

**Comment by Thermatix** [comment]
I had this issue as well and it caused `$` to be added to the end of every line, but I solved it by adding the following to my .vimrc:

    set listchars=tab:›\ ,trail:•,extends:#,nbsp:.

which is probably not what you're looking for but it solve my problem at least.

**Comment by Claudius42** [comment]
@Thermatix: Please find attached a version of your plugin where I fixed the issue. Please feel free to use or adapt.
[indentguides.vim.txt](https://github.com/thaerkh/vim-indentguides/files/1362182/indentguides.vim.txt)

**Comment by thaerkh** [comment]
Hi @Claudius42 , I've merged a very close variant (on by default). List mode, to the best of my knowledge, is needed so that tab indents and dots on the spaces appear correctly, which intended as default behaviour. Thank you for your contribution!
